./a.out screen0width40.txt                           > ../retime/screen0width40.txt
./a.out screen0width80.txt                           > ../retime/screen0width80.txt
./a.out screen1sprites.txt                           > ../retime/screen1sprites.txt
./a.out screen2sprites.txt                           > ../retime/screen2sprites.txt
./a.out screen3sprites.txt                           > ../retime/screen3sprites.txt
./a.out screen5screenoffHMMM3.txt                    > ../retime/screen5screenoffHMMM3.txt
./a.out screen5screenoffHMMM6.txt                    > ../retime/screen5screenoffHMMM6.txt
./a.out screen5screenoffHMMM.txt                     > ../retime/screen5screenoffHMMM.txt
./a.out screen5screenoffHMMV3.txt                    > ../retime/screen5screenoffHMMV3.txt
./a.out screen5screenoffHMMV6.txt                    > ../retime/screen5screenoffHMMV6.txt
./a.out screen5screenoffHMMVcpuread.txt              > ../retime/screen5screenoffHMMVcpuread.txt
./a.out screen5screenoffHMMVcpuwrite.txt             > ../retime/screen5screenoffHMMVcpuwrite.txt
./a.out screen5screenoffHMMVnocpu.txt                > ../retime/screen5screenoffHMMVnocpu.txt
./a.out screen5screenoffHYMM6.txt                    > ../retime/screen5screenoffHYMM6.txt
./a.out screen5screenoffLINE0START.txt               > ../retime/screen5screenoffLINE0START.txt
./a.out screen5screenoffLINE128START.txt             > ../retime/screen5screenoffLINE128START.txt
./a.out screen5screenoffLINE256START.txt             > ../retime/screen5screenoffLINE256START.txt
./a.out screen5screenoffLINE37START.txt              > ../retime/screen5screenoffLINE37START.txt
./a.out screen5screenoffLINEXOR73.txt                > ../retime/screen5screenoffLINEXOR73.txt
./a.out screen5screenoffLMMM1.txt                    > ../retime/screen5screenoffLMMM1.txt
./a.out screen5screenoffLMMM6.txt                    > ../retime/screen5screenoffLMMM6.txt
./a.out screen5screenoffLMMM7.txt                    > ../retime/screen5screenoffLMMM7.txt
./a.out screen5screenoffLMMM.txt                     > ../retime/screen5screenoffLMMM.txt
./a.out screen5screenoffLMMV1.txt                    > ../retime/screen5screenoffLMMV1.txt
./a.out screen5screenoffLMMV6.txt                    > ../retime/screen5screenoffLMMV6.txt
./a.out screen5screenoffLMMV.txt                     > ../retime/screen5screenoffLMMV.txt
./a.out screen5screenoffnocmdcpuread.txt             > ../retime/screen5screenoffnocmdcpuread.txt
./a.out screen5screenoffnocmdcpuwrite.txt            > ../retime/screen5screenoffnocmdcpuwrite.txt
./a.out screen5screenoffnocmdnocpu.txt               > ../retime/screen5screenoffnocmdnocpu.txt
./a.out screen5screenoffYMMM3.txt                    > ../retime/screen5screenoffYMMM3.txt
./a.out screen5screenoffYMMM.txt                     > ../retime/screen5screenoffYMMM.txt
./a.out screen5sprite16x16HMMVcpuread.txt            > ../retime/screen5sprite16x16HMMVcpuread.txt
./a.out screen5sprite16x16HMMVcpuwrite.txt           > ../retime/screen5sprite16x16HMMVcpuwrite.txt
./a.out screen5sprite16x16HMMVnocpu.txt              > ../retime/screen5sprite16x16HMMVnocpu.txt
./a.out screen5sprite16x16nocmdcpuread.txt           > ../retime/screen5sprite16x16nocmdcpuread.txt
./a.out screen5sprite16x16nocmdcpuwrite.txt          > ../retime/screen5sprite16x16nocmdcpuwrite.txt
./a.out screen5sprite16x16nocmdnocpuhalfsprites.txt  > ../retime/screen5sprite16x16nocmdnocpuhalfsprites.txt
./a.out screen5sprite16x16nocmdnocpu.txt             > ../retime/screen5sprite16x16nocmdnocpu.txt
./a.out screen5sprite16x16nocmdnocpu_x1.txt          > ../retime/screen5sprite16x16nocmdnocpu_x1.txt
./a.out screen5sprite16x16nocmdnocpu_x2.txt          > ../retime/screen5sprite16x16nocmdnocpu_x2.txt
./a.out screen5sprite16x16nocmdnocpu_x3.txt          > ../retime/screen5sprite16x16nocmdnocpu_x3.txt
./a.out screen5sprite16x16nocmdnocpu_x4.txt          > ../retime/screen5sprite16x16nocmdnocpu_x4.txt
./a.out screen5sprite8x8HMMVnocpu.txt                > ../retime/screen5sprite8x8HMMVnocpu.txt
./a.out screen5sprite8x8nocmdcpuread.txt             > ../retime/screen5sprite8x8nocmdcpuread.txt
./a.out screen5sprite8x8nocmdcpuwrite.txt            > ../retime/screen5sprite8x8nocmdcpuwrite.txt
./a.out screen5sprite8x8nocmdnocpu.txt               > ../retime/screen5sprite8x8nocmdnocpu.txt
./a.out screen5spritesoffHMMVcpuread.txt             > ../retime/screen5spritesoffHMMVcpuread.txt
./a.out screen5spritesoffHMMVcpuwrite.txt            > ../retime/screen5spritesoffHMMVcpuwrite.txt
./a.out screen5spritesoffnocmdcpuread.txt            > ../retime/screen5spritesoffnocmdcpuread.txt
./a.out screen5spritesoffnocmdcpuwrite2.txt          > ../retime/screen5spritesoffnocmdcpuwrite2.txt
./a.out screen5spritesoffnocmdcpuwrite.txt           > ../retime/screen5spritesoffnocmdcpuwrite.txt
./a.out screen5spritesoffnocmdnocpu.txt              > ../retime/screen5spritesoffnocmdnocpu.txt
./a.out screen6sprites.txt                           > ../retime/screen6sprites.txt
./a.out screen7sprites.cvd.txt                       > ../retime/screen7sprites.cvd.txt
./a.out screen8nospritesHMMVcpuwrite.txt             > ../retime/screen8nospritesHMMVcpuwrite.txt
./a.out screen8nospritesHMMVnocpu.txt                > ../retime/screen8nospritesHMMVnocpu.txt
./a.out screen8nospritesnocmdcpuwrite.txt            > ../retime/screen8nospritesnocmdcpuwrite.txt
./a.out screen8nospritesnocmdnocpu.txt               > ../retime/screen8nospritesnocmdnocpu.txt
./a.out screen8screenoffHMMM.txt                     > ../retime/screen8screenoffHMMM.txt
./a.out screen8screenoffHMMV1.txt                    > ../retime/screen8screenoffHMMV1.txt
./a.out screen8screenoffHMMV6.txt                    > ../retime/screen8screenoffHMMV6.txt
./a.out screen8screenoffHMMVcpuwrite.txt             > ../retime/screen8screenoffHMMVcpuwrite.txt
./a.out screen8screenoffHMMVcpuwrite_wrong_range.txt > ../retime/screen8screenoffHMMVcpuwrite_wrong_range.txt
./a.out screen8screenoffHMMVnocpu.txt                > ../retime/screen8screenoffHMMVnocpu.txt
./a.out screen8screenoffHMMVnocpu_wrong_range.txt    > ../retime/screen8screenoffHMMVnocpu_wrong_range.txt
./a.out screen8screenoffLINE0.txt                    > ../retime/screen8screenoffLINE0.txt
./a.out screen8screenoffLINE37OR.txt                 > ../retime/screen8screenoffLINE37OR.txt
./a.out screen8screenoffLMMM7TIMP.txt                > ../retime/screen8screenoffLMMM7TIMP.txt
./a.out screen8screenoffLMMM.txt                     > ../retime/screen8screenoffLMMM.txt
./a.out screen8screenoffnocmdcpuwrite.txt            > ../retime/screen8screenoffnocmdcpuwrite.txt
./a.out screen8screenoffnocmdnocpu.txt               > ../retime/screen8screenoffnocmdnocpu.txt
./a.out screen8screenoffYMMM1.txt                    > ../retime/screen8screenoffYMMM1.txt
./a.out screen8screenoffYMMM6.txt                    > ../retime/screen8screenoffYMMM6.txt
./a.out screen8screenoffYMMM.txt                     > ../retime/screen8screenoffYMMM.txt
./a.out screen8sprites16x16HMMVcpuwrite.txt          > ../retime/screen8sprites16x16HMMVcpuwrite.txt
./a.out screen8sprites16x16HMMVnocpu.txt             > ../retime/screen8sprites16x16HMMVnocpu.txt
./a.out screen8sprites16x16LINE37OR_HALF.txt         > ../retime/screen8sprites16x16LINE37OR_HALF.txt
./a.out screen8sprites16x16LINE37OR.txt              > ../retime/screen8sprites16x16LINE37OR.txt
./a.out screen8sprites16x16nocmdcpuwrite.txt         > ../retime/screen8sprites16x16nocmdcpuwrite.txt
./a.out screen8sprites16x16nocmdnocpu.txt            > ../retime/screen8sprites16x16nocmdnocpu.txt
./a.out screen8spritesoffLINE37OR.txt                > ../retime/screen8spritesoffLINE37OR.txt
